{"data": "Traceback (most recent call last):\n  File \"/scratch/wh629/research/litl/ling_in_loop/jiant/jiant/utils/zlog.py\", line 39, in log_context\n    yield self\n  File \"/scratch/wh629/research/litl/ling_in_loop/jiant/jiant/proj/main/runscript.py\", line 142, in run_loop\n    runner = setup_runner(\n  File \"/scratch/wh629/research/litl/ling_in_loop/jiant/jiant/proj/main/runscript.py\", line 94, in setup_runner\n    jiant_model_setup.delegate_load_from_path(\n  File \"/scratch/wh629/research/litl/ling_in_loop/jiant/jiant/proj/main/modeling/model_setup.py\", line 78, in delegate_load_from_path\n    weights_dict = torch.load(weights_path)\n  File \"/scratch/wh629/research/litl/ling_in_loop/env/lib/python3.8/site-packages/torch/serialization.py\", line 581, in load\n    with _open_file_like(f, 'rb') as opened_file:\n  File \"/scratch/wh629/research/litl/ling_in_loop/env/lib/python3.8/site-packages/torch/serialization.py\", line 230, in _open_file_like\n    return _open_file(name_or_buffer, mode)\n  File \"/scratch/wh629/research/litl/ling_in_loop/env/lib/python3.8/site-packages/torch/serialization.py\", line 211, in __init__\n    super(_open_file, self).__init__(open(name, mode))\nFileNotFoundError: [Errno 2] No such file or directory: '/scratch/wh629/research/litl/ling_in_loop/models/roberta-large-mnli_only-custom/best.p'\n", "TIMESTAMP": 1608170362.932212}
